on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  check-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Feature Branch
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          # Restrict the push requests to the prefixes feature/ID-[ alpha.num. ID of length 8 ]-... and fix/ID-[ alpha.num. ID of length 8 ]-...
          if [[ $branch_name =~ ^feature\/ID-[0-9A-Za-z]{8}-.*$ || $branch_name =~ ^fix\/ID-[0-9A-Za-z]{8}-.*$ || $branch_name == main ]]; then
            echo "Branch with the correct pattern: $branch_name"
          else
            echo "::error::Invalid branch name: $branch_name"
            exit 1
          fi


  deploy-on-render:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Render.com
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo ${{ github.event_name }}
          CURL_RESULT=$(curl --request PATCH \
              --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }} \
              --header 'accept: application/json' \
              --header 'authorization: Bearer ${{ secrets.RENDER_TOKEN }}' \
              --header 'content-type: application/json' \
              --data '
                      {
                        "autoDeploy": "yes",
                        "branch": "${{ github.ref_name }}"
                      }
                    '
              )
            
            URL_RESULT=$(echo $CURL_RESULT | jq -r '.serviceDetails.url')

            if [ -z "$URL_RESULT" ]; then
              echo "::error::Something went wrong with the deployment on Render.com 🤷"
            fi

            DEPLOY_REQUEST=$(curl --request POST \
                --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
                --header 'accept: application/json' \
                --header 'authorization: Bearer ${{ secrets.RENDER_TOKEN }}' \
                --header 'content-type: application/json' \
                --data '
                  {
                    "clearCache": "do_not_clear"
                  }
                  ')
              
              echo -e "\e[32mIt might take a minute, go on $URL_RESULT 🚀\e[0m"